name: glados
version: 0.1.0.0
github: "githubuser/glados"
license: BSD-3-Clause
author: "Author name here"
maintainer: "example@example.com"
copyright: "2023 Author name here"

extra-source-files:
  - README.md
  - CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/glados#readme>

dependencies:
  - base >= 4.7 && < 5
  - mtl
  - bytestring

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
    - filepath
    - directory

executables:
  glados-exe:
    main: Main.hs
    source-dirs: app
    other-modules:
      - Paths_glados
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - glados
      - split
  eval-exe:
    main: BinaryEvaluation.hs
    source-dirs: app
    other-modules:
      - Paths_glados
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - glados
      - split
      - utf8-string

tests:
  glados-test:
    main: Spec.hs
    source-dirs: test
    other-modules:
      - UnitTestParser
      - UnitTestCompiler
      - UnitTestEvaluation
      - Paths_glados
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - HUnit >= 1.6.2.0
      - glados

extra-deps:
  - split-0.2.3.4
