name: Build and Test Stack project

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: haskell:8.10.4-buster

    steps:
      - uses: actions/checkout@v2

      - name: Change owner of /github/home/
        run: sudo chown -R $(whoami) /github/home/

      - name: Build
        run: |
          stack setup --allow-different-user
          stack build --allow-different-user

      - name: Test
        run: ./test/test.sh
        # When we have a test suite, we can use the following instead:
        # run: |
        #   stack test --coverage --allow-different-user
