name: Build and Test Stack project

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: haskell:8.10.4
    env:
      STACK_ROOT: /root/.stack


    steps:
      - uses: actions/checkout@v3

      - name: Cache stack
        uses: actions/cache@v2
        with:
          path: ${{ env.STACK_ROOT }}
          key: ${{ runner.os }}-stack-${{ hashFiles('**/stack.yaml') }}
          restore-keys: |
            ${{ runner.os }}-stack-

      - name: Build
        run: |
          stack setup --allow-different-user
          stack build --allow-different-user
          cp $(stack path --local-install-root)/bin/glados-exe ./glados

      - name: Test
        run: |
          ls -lR
          ./test/test.sh
        # When we have a test suite, we can use the following instead:
        # run: |
        #   stack test --coverage --allow-different-user
