name: Build and Test Stack project

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 💽 Install OS Packages
        uses: actions/cache@v1
        with:
          apt-get: libgmp-dev

      - name: 📥 Checkout repository
        uses: actions/checkout@v1

      - name: 🧰 Setup Stack
        uses: haskell/actions/setup@v1

      - name: 📸 Build Snapshot
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          stack --no-terminal test --bench --only-snapshot
      - name: 🔨 Build & Test
        run: |
          make
          make test
