name: Build and Test Stack project

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up build environment
        run: |
          sudo apt-get update
          sudo apt install -y haskell-stack
          stack upgrade
        shell: bash

      - name: Build the project
        run: |
          stack build
        working-directory: ${{ github.workspace }}

      - name: Run tests
        run: |
          stack test --no-terminal
        working-directory: ${{ github.workspace }}
