name: Build and Test Stack project

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 💽 Install OS Packages
        uses: actions/cache@v1
        with:
          apt-get: libgmp-dev

      - name: 📥 Checkout repository
        uses: actions/checkout@v2

      - name: Set up Haskell
        uses: actions/setup-haskell@v2
        with:
          ghc-version: "8.10.7"
          cabal-version: "3.4.0.0"

      - name: 📸 Build Snapshot
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          stack --no-terminal test --bench --only-snapshot
      - name: 🔨 Build & Test
        run: |
          make
          make test
