name: Build and publish a release

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    container: haskell:8.10.4
    env:
      STACK_ROOT: /root/.stack

    steps:
      - uses: actions/checkout@v3

      - name: Change working directory
        run: cd ${{ env.STACK_ROOT }}

      - name: Build the project
        run: |
          stack setup --allow-different-user
          stack build --allow-different-user

      - name: Extract the executable
        run: |
          cp $(stack path --local-install-root)/bin/glados-exe glados
          cp $(stack path --local-install-root)/bin/eval-exe eval

      - name: Publish a release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            glados
            eval
          body: |
            This is an automated release.
